# Generated by Django 2.2.11 on 2020-04-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attachment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
