# Generated by Django 2.2.11 on 2020-04-08 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fil',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
