# Generated by Django 2.2.11 on 2020-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0002_card_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
