# Generated by Django 2.2.11 on 2020-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0003_auto_20200409_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
