# Generated by Django 2.2.11 on 2020-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0004_card_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
