# Generated by Django 2.2.11 on 2020-04-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0005_auto_20200409_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='attachment',
            new_name='atmnt',
        ),
    ]
