# Generated by Django 2.2.11 on 2020-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0005_auto_20200408_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attachment',
            field=models.CharField(max_length=64),
        ),
    ]
