# Generated by Django 2.2.11 on 2020-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0006_auto_20200409_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='atmnt',
            new_name='atmnt0',
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt1',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt2',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt3',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt4',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt5',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt6',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt7',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt8',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='card',
            name='atmnt9',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
